export const site = {
  about: { 
    heading: "I'm Matt Jared",
    subheading: "Sales Engineer based in Austin, USA.",
    mission: "Empowering teams to solve complex challenges at scale.",
    bio: "I’m a self-taught software developer delivering high-impact solutions. I’ve worked at startups and a large public company. Today, I’m a Sales Engineer at Vercel, helping organizations build fast sites with fast teams."
  },
  careerCards: [
    { logo: '▲', title: 'Senior Sales Engineer', company: 'Vercel', date: 'Jan 2023 - Present' },
    { logo: '🌎', title: 'Senior Developer', company: 'Atlassian', date: 'June 2018 - Jan 2023' },
    { logo: '🦓', title: 'Frontend Developer', company: 'The Zebra', date: 'Jan 2015 - June 2018' },
  ],
  recentAppearances: [
    { logo: '🌐', title: 'The WordPress Edge', description: 'A look at the future of Headless WordPress', cta: 'Watch the Video', url: 'https://www.youtube.com/watch?v=5ECzvKmOiMg' },
    { logo: '🏄🏻‍♂️', title: 'How to scale your business with AI', description: 'A look at how AI can help scale your business', cta: 'Watch the Video', url: 'https://www.youtube.com/watch?v=9h_dFCNSiQ4' },
  ],
  projects: [
    { logo: '🔟', title: 'How much is 10mb?', desciption: 'A site pushing the limits of what can go into 10mb', url: 'https://how-much-is-10mb.yay.boo/' },
    { logo: '🏀', title: 'Random Hooper', desciption: 'An API to generate random NBA player names', url: 'https://random-hooper.vercel.app/' },
    { logo: '📊', title: 'Scorelord', desciption: 'Full stack app to track daily scores and post to Slack', url: 'https://github.com/mattjared/scorelord',},
    { logo: '⚽', title: 'Server Side Football Site', desciption: 'Using SS R to display English Soccer team data', url: 'https://server-side-football-site.vercel.app/',},
    { logo: '🎮', title: 'Client Side Football Site', desciption: 'Using CSR to display English Soccer team data', url: 'https://client-side-football-site.vercel.app/',},
    { logo: '📱', title: 'Football Clubs API', desciption: 'Supabase + Next.js with all Wikipedia data showing English soccer teams', url: 'https://github.com/mattjared/football-clubs-api',},
    { logo: '🚀', title: 'Next in line', desciption: 'Hype site for pre launch startups and drops', url: 'https://next-in-line.vercel.app/',},
    { logo: '🤖', title: 'Next.js AI Lite', desciption: 'Minimal AI chatbot start built with Next.js', url: 'https://github.com/mattjared/nextjs-ai-lite',},
    { logo: '🎯', title: 'React Chicago Site', desciption: 'Rebuilt the React Chicago Meetup site with Next.js', url: 'https://github.com/mattjared/react-chicago',},
    { logo: '📈', title: 'Annotated Hinkie Letter', desciption: 'Tracking how the process unfolded', url: 'https://github.com/mattjared/annotated-hinkie-letter',},
    { logo: '📚', title: 'Book tracking site', desciption: 'Tracking books everyone likes', url: 'https://github.com/mattjared/vercel-books',},
    { logo: '🎉', title: 'Party Pad', desciption: 'Birthday party invitation site', url: 'https://github.com/mattjared/party-pad',},
    { logo: '🔄', title: 'Close Tabs', desciption: 'Chrome extension for closing tabs that automatically open for zoom and notion and others', url: 'https://github.com/mattjared/close-tabs',},
    { logo: '🎨', title: 'Homepage GTP', desciption: 'v0 but made by me and not very good 😂', url: 'https://github.com/mattjared/homepageGPT',},
    { logo: '🎧', title: 'Bingeboard', desciption: 'Greatest quotes from the Binge Mode podcast on a soundboard', url: 'https://github.com/mattjared/binge-board',},
    { logo: '🎪', title: 'NBA Colors', desciption: 'Package with NBA colors', url: 'https://github.com/mattjared/nba-color',},
  ],
  socials: [
    { logo: "🔮", service: "Bento", url: "https://bento.me/mattjared" },
    { logo: "🐧", service: 'CodePen', url: 'https://codepen.io/matt_jared' },
    { logo: "🐱", service: 'GitHub', url: 'https://github.com/mattjared' },
    { logo: "💼", service: 'LinkedIn', url: 'https://www.linkedin.com/in/mattjared9' },
    { logo: "👨‍💻", service: 'dev.to', url: 'https://dev.to/mattjared' },
    { logo: "🎨", service: 'Dribbble', url: 'https://dribbble.com/matt_jared' },
    { logo: "📦", service: 'npm', url: 'https://www.npmjs.com/~mattjared' },
    { logo: "🏗️", service: 'Code Sandbox', url: 'https://codesandbox.io/u/mattjared' },
    { logo: "🌐", service: 'Polywork', url: 'https://www.polywork.com/mattjared' },
    { logo: "📚", service: 'Stack Overflow', url: 'https://stackoverflow.com/users/2658883/matt-jared' },
    { logo: "🎥", service: 'YouTube', url: 'https://www.youtube.com/@mattjared' },
    { logo: "🐋", service: 'Album Whale', url: 'https://albumwhale.com/matt-jared' },
    { logo: "☕", service: 'Buy Me a Coffee', url: 'https://www.buymeacoffee.com/mattjared' },
  ],
  career: [
    { organization: "Vercel", role: "Sales Engineer" },
    { organization: "Atlassian", role: "Senior Developer" },
    { organization: "The Zebra", role: "Front End Developer" },
    { organization: "Techstars", role: "Hackstar" },
    { organization: "Cratejoy", role: "Designer / Developer" },
    { organization: "Ohio University", role: "BBA Marketing" },
  ]
}
