export const site = {
  about: { 
    heading: "I'm Matt Jared",
    subheading: "I'm Matt Jared, Sales Engineer based in Austin, Texas USA.",
    bio: "I'm a marketer turned self-taught developer turned sales engineer turned sales leader. I have worked at and alongside startups, a large public company and today I help enable fast teams to build fast sites at Vercel. I love building things - web sites, teams, projects, companies, whatever - and sharing what I’ve learned along the way",
    howtowork: "This site is my attempt at sharing everything I know. I'm available an a project basis to help your startup or project get to market. "
  },
  careerCards: [
    { title: 'Sales Engineer Manager', company: 'Vercel', date: 'January 2025 - Present' },
    { title: 'Senior Sales Engineer', company: 'Vercel', date: 'January 2023 - December 2024' },
    { title: 'Senior Developer', company: 'Atlassian', date: 'June 2018 - January 2023' },
    { title: 'Frontend Developer', company: 'The Zebra', date: 'January 2015 - June 2018' },
  ],
  recentAppearances: [
    { title: 'The WordPress Edge', description: 'A look at the future of Headless WordPress', cta: 'Watch the Video', url: 'https://www.youtube.com/watch?v=5ECzvKmOiMg' },
    { title: 'How to scale your business with AI', description: 'A look at how AI can help scale your business', cta: 'Watch the Video', url: 'https://www.youtube.com/watch?v=9h_dFCNSiQ4' },
    { title: 'Ship 2025 Anatomy of a Fast Site', description: 'What does a FAST site look like? How do you make one?', cta: 'Watch the Video', url: 'https://www.youtube.com/watch?v=cPLmB3PRMCY' },
    { title: 'Public Vercel Appearances', description: "Everything I've done that's publicly available while at Vercel", url: "/blog/public-vercel-ships" }
  ],
  projects: [
    { title: 'Void', description: 'A chrome extension for taking notes and focus', url: 'https://void-neon.vercel.app/' },
    { title: 'Scorelord', description: 'Full stack app to track daily scores and post to Slack', url: 'https://github.com/mattjared/scorelord',},
    { title: 'How much is 10mb?', description: 'A site pushing the limits of what can go into 10mb', url: 'https://how-much-is-10mb.yay.boo/' },
    { title: 'Random Hooper', description: 'An API to generate random NBA player names', url: 'https://random-hooper.vercel.app/' },
    { title: 'Server Side Football Site', description: 'Using SS R to display English Soccer team data', url: 'https://server-side-football-site.vercel.app/',},
    { title: 'Client Side Football Site', description: 'Using CSR to display English Soccer team data', url: 'https://client-side-football-site.vercel.app/',},
    { title: 'Football Clubs API', description: 'Supabase + Next.js with all Wikipedia data showing English soccer teams', url: 'https://github.com/mattjared/football-clubs-api',},
    { title: 'Next in line', description: 'Hype site for pre launch startups and drops', url: 'https://next-in-line.vercel.app/',},
    { title: 'Next.js AI Lite', description: 'Minimal AI chatbot start built with Next.js', url: 'https://github.com/mattjared/nextjs-ai-lite',},
    { title: 'React Chicago Site', description: 'Rebuilt the React Chicago Meetup site with Next.js', url: 'https://github.com/mattjared/react-chicago',},
    { title: 'Annotated Hinkie Letter', description: 'Tracking how the process unfolded', url: 'https://github.com/mattjared/annotated-hinkie-letter',},
    { title: 'Book tracking site', description: 'Tracking books everyone likes', url: 'https://github.com/mattjared/vercel-books',},
    { title: 'Party Pad', description: 'Birthday party invitation site', url: 'https://github.com/mattjared/party-pad',},
    { title: 'Close Tabs', description: 'Chrome extension for closing tabs that automatically open for zoom and notion and others', url: 'https://github.com/mattjared/close-tabs',},
    { title: 'Homepage GPT', description: 'v0 but made by me and not very good 😂', url: 'https://github.com/mattjared/homepageGPT',},
    { title: 'Bingeboard', description: 'Greatest quotes from the Binge Mode podcast on a soundboard', url: 'https://github.com/mattjared/binge-board',},
    { title: 'NBA Colors', description: 'Package with NBA colors', url: 'https://github.com/mattjared/nba-color',},
  ],
  socials: [
    { service: 'CodePen', url: 'https://codepen.io/matt_jared' },
    { service: 'GitHub', url: 'https://github.com/mattjared' },
    { service: 'LinkedIn', url: 'https://www.linkedin.com/in/mattjared9' },
    // { service: 'dev.to', url: 'https://dev.to/mattjared' },
    // { service: 'Dribbble', url: 'https://dribbble.com/matt_jared' },
    // { service: 'npm', url: 'https://www.npmjs.com/~mattjared' },
    // { service: 'Code Sandbox', url: 'https://codesandbox.io/u/mattjared' },
    // { service: 'Stack Overflow', url: 'https://stackoverflow.com/users/2658883/matt-jared' },
    // { service: 'YouTube', url: 'https://www.youtube.com/@mattjared' },
    // { service: 'Buy Me a Coffee', url: 'https://www.buymeacoffee.com/mattjared' },
  ],
  career: [
    { organization: "Vercel", role: "Senior Sales Engineer", role2: "Sales Engineering Manager"},
    // { organization: "Vercel", role: "Senior Sales Engineer" },
    // { organization: "Vercel", role: "Sales Engineer" },
    { organization: "Atlassian", role: "Senior Developer"},
    { organization: "The Zebra", role: "Front End Developer", role2: "Front End Engineer, II" },
    { organization: "Techstars", role: "Hackstar" },
    { organization: "Cratejoy", role: "Designer / Developer" },
    { organization: "Ohio University", role: "BBA, Marketing" },
  ]
}
