import Head from 'next/head'
import Image from 'next/image'
import fs, { read } from 'fs';
import matter from 'gray-matter';
import Link from 'next/link';

export async function getStaticProps() {
  const files = fs.readdirSync('posts');

  const posts = files.map((fileName) => {
    const slug = fileName.replace('.md', '');
    const readFile = fs.readFileSync(`posts/${fileName}`, 'utf-8');
    const { data: frontmatter } = matter(readFile);

    return {
      slug,
      frontmatter
    };
  });

  return {
    props: {
      posts,
    },
  }
}

export default function Home({ posts }: {posts: any}) {
  return (
    <>
      <Head>
        <title>Matt Jared</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <section>
          <article className="css-gui-1vyjrns">
            <h2 className="text-2xl font-semibold mb-2">About</h2>
            <p className="css-gui-za5pjy">
              I am a self taught software engineer who loves solving problems and delivering high impact solutions. After starting my career in marketing I taught myself to code and spent years working on engineering teams at startups and most recently at Atlassian. I recently transitioned to Sales Engineering at Vercel where I live at the  cross section between sales and web development helping companies and developers build the future of the web.
            </p>
          </article>
        </section>
        <section className="blog-grid">
          {posts.map(({slug, frontmatter}: { slug: any, frontmatter: any}) => (
            (frontmatter.published === true && 
              <Link href={`/post/${slug}`} key={slug} className="blog-card">
                {/* <Image
                  src={`/${frontmatter.socialImage}`}
                  alt={frontmatter.title}
                  className="css-gui-bj5kgm"
                  width={100}
                  height={100}
                /> */}
                <h2 className="text-2xl font-semibold mb-2">{frontmatter.title}</h2>
                <p className="css-gui-za5pjy">Published: {frontmatter.post_date}</p>
              </Link>
            )            
          ))}
        </section>
        <blockquote className="pl-8 ml-0 w-full border-l-4 border-current">
          <p className="text-3xl mb-4 font-semibold">
            What if you stopped trying to think your way through it <br />
            and started to act your way through it?
          </p>
          <p className="opacity-60">- James Clear</p>
        </blockquote>  
        <article className="label-cards">
          <div className="label-card">
            <h4 className="label-card-headline">Experience</h4>
            <div className="label-card-col">
              <ul>
                <li>Vercel</li>
                <li>Atlassian</li>
                <li>The Zebra</li>
                <li>Techstars</li>
                <li>Ohio University</li>
              </ul>
            </div>
          </div>
          <div className="label-card">
            <h4 className="label-card-headline">Socials</h4>
            <div className="label-card-row">
              <div className="label-card-col">
                <p className="label-card-item"><a href="https://codepen.io/matt_jared">CodePen</a></p>
                <p className="label-card-item"><a href="https://github.com/mattjared">GitHub</a></p>
                <p className="label-card-item"><a href="https://www.linkedin.com/in/mattjared9">LinkedIn</a></p>
                <p className="label-card-item"><a href="https://dev.to/mattjared">dev.to</a></p>
                <p className="label-card-item"><a href="https://twitter.com/matt_jared">Twitter</a></p>
              </div>
              <div className="label-card-col">
                <p className="label-card-item"><a href="https://dribbble.com/matt_jared">Dribbble</a></p>
                <p className="label-card-item"><a href="https://www.npmjs.com/~mattjared">npm</a></p>
                <p className="label-card-item"><a href="https://codesandbox.io/u/mattjared">Code Sandbox</a></p>
                <p className="label-card-item"><a href="https://www.polywork.com/mattjared">Polywork</a></p>
                <p className="label-card-item"><a href="https://stackoverflow.com/users/2658883/matt-jared">Stack Overflow</a> </p> 
              </div>
            </div>
          </div>
        </article>
      </div>
    </>
  )
}
